[build]
command = "npm run build"
publish = "dist"

[[redirects]]
  from = "/search"
  to = "https://api.mysearch.com"
  status = 200
  force = true 
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"
