


[[redirects]] 
  from = "/search"
  to = "/index.html"
  status = 200
  force = true 
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"
  command = "npm run build"
publish = "dist"
base = "project"

  
